## Numpy


In [3]:
import numpy as np

## Crear arreglos

In [4]:
x = np.array([10,20,30,40,50,60]) #Creó un arreglo o un tensor
x

array([10, 20, 30, 40, 50, 60])

In [5]:
x[4]

50

In [6]:
x[1:3]

array([20, 30])

In [7]:
y = np.linspace(10,20,2) #crea particiones de un intervalo.
y

array([10., 20.])

In [10]:
z = np.arange(1,21,.5) #Crea un array 
z

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5,
       12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. , 16.5, 17. ,
       17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5])

In [13]:
ze = np.zeros((4,4)) #Crea un arreglo de n cantidad de elementos valor 0. También se puede generar en una matriz
ze

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
unos = np.ones((4,4)) # Similar a np.zeros pero con unos
unos

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
y = np.array([[10,20,40,60],[15,25,35,45]])
np.zeros_like(y) #Genera una matriz o un arreglo con la misma estructura que la variable o argumento

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [18]:
y = np.array([[10,20,40,60],[15,25,35,45]])
rango = y.ndim
dimensiones = y.shape
print(f"El rango del tensor es: {rango}, las dimensiones son {dimensiones}")

El rango del tensor es: 2, las dimensiones son (2, 4)


In [ ]:
x = np.array([10,20,30,40,50,60])
y = np.array([[10,20,40,60],[15,25,35,45]])


In [19]:
x[2] #Cuando es un vector de dimensión 1,n

30

In [20]:
y[0,3] #Cuando son matrices o tienen vectores de m,n

60

In [21]:
rango = y.ndim
dimensiones = y.shape
print(y[0,3]) #La cantidad de argumentos es igual a la cantidad del rango. El rango es la cantidad de elementos o dimensiones que tiene el tensor para representar o extraer los valores 
#print(y[0][3]) Es lo mismo que el de la línea anterior.
print(f"El rango del tensor es:{rango}, las dimensiones son {dimensiones}") 

60
El rango del tensor es:2, las dimensiones son (2, 4)


In [23]:
y = np.array([[[10,20,30,40,50],[33,44,55,66,77]],[[111,222,333,444,555],[777,888,999,232,656]]])
rango = y.ndim
dimensiones = y.shape
print(f"El rango del tensor es: {rango}, las dimensiones son {dimensiones}")

El rango del tensor es: 3, las dimensiones son (2, 2, 5)


In [25]:
print(y[0,0,4]) #para extraer un dato se necesitan 3 números debido a que es de rango 3

50


### Operaciones

In [26]:
v = np.array([1,2,3,4])
w = np.array([5,6,7,8])

In [27]:
print("suma: ", v + w)
print("resta: ", v - w)
print("multiplicación: ", v * w)
print("división: ", v / w)
print("modulo: ", v % w)
print("mult escalar: ", 2*w)
print("suma escalar: ", 5 + v)
print("resta escalar: ", 4 - w)
print("division escalar: ", w / 8)
print("modulo escalar: ", w % 2)

suma:  [ 6  8 10 12]
resta:  [-4 -4 -4 -4]
multiplicación:  [ 5 12 21 32]
división:  [0.2        0.33333333 0.42857143 0.5       ]
modulo:  [1 2 3 4]
mult escalar:  [10 12 14 16]
suma escalar:  [6 7 8 9]
resta escalar:  [-1 -2 -3 -4]
division escalar:  [0.625 0.75  0.875 1.   ]
modulo escalar:  [1 0 1 0]


#### Operaciones de Agregación o NaN

In [28]:
x = np.array([1,2, 3,4, 5, 6, 7, 3, 3, 4, 5])
x_nan = np.array([1, 2, 3, 4, 5, 6, 7, np.nan, 5, 9, np.nan])

In [31]:
print(np.mean(x))
print(np.nanmean(x_nan))

3.909090909090909
4.666666666666667


In [32]:
print(np.std(x))
print(np.nanstd(x_nan))

1.6762808104168887
2.357022603955158


In [33]:
print(np.max(x))
print(np.nanmax(x_nan))

7
9.0


In [34]:
print(np.sum(x))
print(np.nansum(x_nan))

43
42.0


Existen fórmulas de agregación que toman en cuenta los nan para poder operarlos

In [35]:
print(np.mean(x))
print(np.nanmean(x_nan))
print(np.median(x))
print(np.nanmedian(x_nan))
print(np.std(x))
print(np.nanstd(x_nan))
print(np.max(x))
print(np.nanmax(x_nan))
print(np.min(x))
print(np.nanmin(x_nan))
print(np.var(x))
print(np.nanvar(x_nan))
print(np.sum(x))
print(np.nansum(x_nan))
print(np.prod(x))
print(np.nanprod(x))

3.909090909090909
4.666666666666667
4.0
5.0
1.6762808104168887
2.357022603955158
7
9.0
1
1.0
2.809917355371901
5.5555555555555545
43
42.0
907200
907200


### Reshape

In [38]:
x = np.arange(0,10,1)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np.reshape(x,(2,5)) #para poder hacer reshape, la data lo tiene que permitir es decir, no se puede pedir una matriz (3,5) ya que no hay 15 datos.

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### Performance

In [40]:
from time import time

In [50]:
x = np.linspace(1,10000000, 20000000)
b0 = 5
b1 = 2

In [43]:
y = np.empty_like(x)

inicio = time()
for index, value in enumerate(x):
    y[index]= b0 + b1 * value
fin = time()
print(f"El tiempo de ejecución fue de: {fin-inicio}")

El tiempo de ejecución fue de: 10.595563888549805


### Solución con Numpy

In [51]:
#x = np.arange(0,10,1)
#x

vect1=np.ones_like(x).reshape(-1,1)
x = np.reshape(x,(-1,1))
A = np.hstack([x, vect1])
betas = np.array([[b1],[b0]])

inicio = time()
y1 = np.matmul(A,betas)
fin = time()
print(f"El tiempo de ejecución fue de: {fin-inicio}")

El tiempo de ejecución fue de: 0.1405954360961914
